openapi: 3.0.0
info:
  description: This is a simple API for managing beds in a system.
  version: "1.0.0"
  title: Bed Management API
  contact:
    email: vedic20052005@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:5000
    description: Local server
tags:
  - name: beds
    description: Operations related to bed management
paths:
  /beds:
    get:
      tags:
        - beds
      summary: Retrieve bed information
      description: |
        Dynamically filter and retrieve bed information based on query parameters.
      operationId: getBeds
      parameters:
        - name: Status
          in: query
          description: Filter by bed status (e.g., 'Occupied', 'Available')
          required: false
          schema:
            type: string
        - name: Type
          in: query
          description: Filter by bed type (e.g., 'Private', 'Shared')
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Bed information matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    BedID:
                      type: integer
                    Status:
                      type: string
                    Type:
                      type: string
                    other_fields:
                      type: string
                      description: Additional fields related to bed information
        '400':
          description: Invalid query parameters
  /set_bed:
    post:
      tags:
        - beds
      summary: Update a bed's status and/or Pid
      description: |
        Update the status and/or Pid of a bed given its BedID.
      operationId: setBed
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: Occupied
                  description: The new status of the bed.
                Pid:
                  type: integer
                  example: 1
                  description: The new patient ID for the bed.
                bedID:
                  type: integer
                  example: 135
                  description: The unique identifier of the bed to be updated.
              required:
                - bedID
      responses:
        '200':
          description: Update successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Update successful
        '400':
          description: Missing 'bedID' or both 'status' and 'Pid' are missing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing 'bedID' or both 'status' and 'Pid' are missing in the request.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred during the update.
